from tkinter import *
from tkinter.ttk import *
from PIL import Image, ImageTk
import customtkinter

class App():
    def __init__(self):
        self.tela = customtkinter.CTk()
        customtkinter.set_appearance_mode("Dark")
        self.tela.iconbitmap("./img/1923767.ico")
        self.tela.title("cad pessoa")
        self.tela.geometry("500x300")
        self.tela.resizable(False,False)
        self.layout1()
        self.tela.mainloop()
    def layout1(self):
        self.lb1 = customtkinter.CTkLabel(self.tela,text="Nome")
        self.lb1.place(relx=0.01,rely=0.1,relwidth=0.1,relheight=0.1)
        self.lb2 = customtkinter.CTkLabel(self.tela,text="Telefone")
        self.lb2.place(relx=0.52,rely=0.1,relwidth=0.1,relheight=0.1)
        self.ent1 = customtkinter.CTkEntry(self.tela)
        self.ent1.place(relx=0.11,rely=0.1,relwidth=0.4,relheight=0.1)
        self.ent2 = customtkinter.CTkEntry(self.tela)
        self.ent2.place(relx=0.64,rely=0.1,relwidth=0.35,relheight=0.1)
        self.lb3 = customtkinter.CTkLabel(self.tela,text="CPF/RG")
        self.lb3.place(relx=0.01,rely=0.22,relwidth=0.1,relheight=0.1)
        self.lb4 = customtkinter.CTkLabel(self.tela,text="Endereço")
        self.lb4.place(relx=0.52,rely=0.22,relwidth=0.11,relheight=0.1)
        self.ent3 = customtkinter.CTkEntry(self.tela)
        self.ent3.place(relx=0.11,rely=0.22,relwidth=0.4,relheight=0.1)
        self.ent4 = customtkinter.CTkEntry(self.tela)
        self.ent4.place(relx=0.64,rely=0.22,relwidth=0.35,relheight=0.1)
        self.bt1 = customtkinter.CTkButton(self.tela,text="Add",command=self.add_user)
        self.bt1.place(relx=0.11,rely=0.34,relwidth=0.4,relheight=0.1)
        self.sw1 = customtkinter.CTkSwitch(self.tela,text="CLT",onvalue="Sim",offvalue="Não")
        self.sw1.place(relx=0.64,rely=0.34,relwidth=0.35,relheight=0.1)
        self.fr1 = customtkinter.CTkFrame(self.tela)
        self.fr1.place(relx=0.05,rely=0.46,relwidth=0.9,relheight=0.5)
        self.listTree = Treeview(self.fr1,columns=['c1','c2','c3','c4','c5'])
        self.listTree.heading("#0",text="")
        self.listTree.heading("#1",text="Nome")
        self.listTree.heading("#2",text="Telefone")
        self.listTree.heading("#3",text="CPF/RG")
        self.listTree.heading("#4",text="Endereço")
        self.listTree.heading("#5",text="CLT")
        self.listTree.column("#0",width=1)
        self.listTree.column("#1",width=50)
        self.listTree.column("#2",width=50)
        self.listTree.column("#3",width=50)
        self.listTree.column("#4",width=50)
        self.listTree.column("#5",width=50)
        self.listTree.place(relx=0,rely=0,relwidth=0.97,relheight=1)
        self.scroll1 = Scrollbar(self.fr1,orient="vertical")
        self.listTree.configure(yscrollcommand=self.scroll1.set)
        self.scroll1.place(relx=0.97,rely=0,relwidth=0.03,relheight=1)
    def add_user(self):
        self.listTree.insert("",END,values=[self.ent1.get(),self.ent2.get(),self.ent3.get(),self.ent4.get(),self.sw1.get()])

App()